//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPulperia
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCompra
    {
        public int IDDETALLECOMPRA { get; set; }
        public int IDCOMPRA { get; set; }
        public int IDPRODUCTO { get; set; }
        public int CANTIDADDC { get; set; }
        public decimal PRECIODC { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
